name: creative_booking_system
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Default icons
  cupertino_icons: ^1.0.2

  # Networking
  http: ^1.2.0

  # Fonts & Styling
  google_fonts: ^6.1.0

  # Date Formatting (For Booking Screen)
  intl: ^0.19.0

  # State Management (Optional for future use)
  flutter_riverpod: ^2.4.9
  
  # Local Storage (For future Login/Auth)
  shared_preferences: ^2.2.2

  # File and Image Pickers
  image_picker: ^1.2.1
  file_picker: ^8.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
